### ISSUE TITLE
Filtering confusion with multiple handles

### ISSUE THREAD

**Issue by nitriques** [symphonists/textboxfield#2]
AS per https://github.com/psychoticmeow/textboxfield/pull/3

When filtering by handle, the latest handle created with this suffix always comes up. (i.e. handle-2 in our case.

The way we fix this is by using a `regexp: ^{$handle}$` but it feels kind of hacky....

I do not know how to fix this... the only way I can think of would be to to a SQL query to check for a perfect match on the handle and revert to value....

//cc @beaubbe @avandalinshorts

**Comment by jonmifsud** [comment]
@nitriques just seen this, did you ever get to work around/fix it?  The way the field works is a bit funny.. in the sense that it always searches both field and value as far as I know.

**Comment by nitriques** [comment]
> did you ever get to work around/fix it?

work around as per the issue (using the regexp trick). 

I think that the best fit would be to add a new filter as per https://github.com/symphonists/textboxfield/blob/master/fields/field.textbox.php#L711 . One could then do `handle: {$value}`

> The way the field works is a bit funny.. in the sense that it always searches both field and value as far as I know.

Yes since this is also how the core input field works.
